### ISSUE TITLE
Consumers problem

### ISSUE THREAD

**Issue by chubz** [djangobot/djangobot#3]
Hi,
I've setup a project with channels and djangobot.
I've managed to run the bot and I get the trace of it receiving messages from slack.
It should the use the channels.Channel(channel_name).send({'text': pack(msg)}). However I don't seem to get those messages in my consumer functions.
Is this due to changes in channels that are active since v1.0.0?

Is there any test project that has code examples?
I'm trying this out on local and runserver covers and listens on the defined slack.message and slack.hello channels.

I also noticed that bot stops working on my production setup after a few moments. that Sending trace print dies but there is no other discernible information to debug from.

**Comment by sburns** [comment]
I haven't had a chance to look at what broke in Channels 1.0 but Djangobot likely doesn't work because I think an upgrade to Daphne is also required. djangobot serves a similar role as daphne as being a long-running server that transfers messages between slack and django consumers.

**Comment by chubz** [comment]
Hi, I got it working, updating to channels 1.0.2 and making sure channel_layers was defined okay was the key. I hope that is the end of it.

It seemed like channels.Channel().send was unusable outside django (shell, djangobot, other standalone processes).

I can confirm it works on 1.0.2 and daphne 1.0.0, I'll close this issue.

Are there any instructions on how the bot would be usable inside django project. Seems like just calling send on slack.send is rather limited. No chance to get channel lists, user lists, direct messaging etc.
My example is integrating a command and resolving the message into something I send back via the bot instead of the response_url provided by slack. If you are up for discussion I'll get in contact with you via twitter or by other means.

**Comment by sburns** [comment]
@chubz glad you got it working! 

There are two ways to get data from Slack. The Real-Time Messaging API implemented in Websockets provides a stream of fast-moving data like chat messages, typing status, etc. 

Slower moving data like a list of channels, users profiles, etc is provided in standard HTTP requests. You could use the excellent Requests library for this. 

Note that direct messaging should be able to be done with slack.send. You just need to provide the correct channel.

**Comment by chubz** [comment]
Should have been more clear in my explanation. I though of something along the lines:
from djangobot import get_active_bot
Or maybe a class based consumer that exposes channels path like:
'bot.list_channels', 'bot.list_users', 
something RPC like.

I understand though that another slack api client or reusing the djangobot.client providing the same token would do just as easily or better since it is directly connected to slack api over the same token.
Thanks for answering.
